#[derive(Debug, serde::Serialize, serde::Deserialize, PartialEq, Eq, Clone)]
pub enum LanguageCode {
    Abkhazian,
    Afar,
    Afrikaans,
    Akan,
    Albanian,
    Amharic,
    Arabic,
    Aragonese,
    Armenian,
    Assamese,
    Avaric,
    Avestan,
    Aymara,
    Azerbaijani,
    Bambara,
    Bashkir,
    Basque,
    Belarusian,
    Bengali,
    Bislama,
    Bosnian,
    Breton,
    Bulgarian,
    Burmese,
    Catalan,
    Chamorro,
    Chechen,
    Chichewa,
    Chinese,
    ChurchSlavonic,
    Chuvash,
    Cornish,
    Corsican,
    Cree,
    Croatian,
    Czech,
    Danish,
    Divehi,
    Dutch,
    Dzongkha,
    English,
    Esperanto,
    Estonian,
    Ewe,
    Faroese,
    Fijian,
    Finnish,
    French,
    WesternFrisian,
    Fulah,
    Gaelic,
    Galician,
    Ganda,
    Georgian,
    German,
    Greek,
    Kalaallisut,
    Guarani,
    Gujarati,
    Haitian,
    Hausa,
    Hebrew,
    Herero,
    Hindi,
    HiriMotu,
    Hungarian,
    Icelandic,
    Ido,
    Igbo,
    Indonesian,
    Interlingua,
    Interlingue,
    Inuktitut,
    Inupiaq,
    Irish,
    Italian,
    Japanese,
    Javanese,
    Kannada,
    Kanuri,
    Kashmiri,
    Kazakh,
    CentralKhmer,
    Kikuyu,
    Kinyarwanda,
    Kyrgyz,
    Komi,
    Kongo,
    Korean,
    Kuanyama,
    Kurdish,
    Lao,
    Latin,
    Latvian,
    Limburgan,
    Lingala,
    Lithuanian,
    LubaKatanga,
    Luxembourgish,
    Macedonian,
    Malagasy,
    Malay,
    Malayalam,
    Maltese,
    Manx,
    Maori,
    Marathi,
    Marshallese,
    Mongolian,
    Nauru,
    Navajo,
    NorthNdebele,
    SouthNdebele,
    Ndonga,
    Nepali,
    Norwegian,
    NorwegianBokmål,
    NorwegianNynorsk,
    Occitan,
    Ojibwa,
    Oriya,
    Oromo,
    Ossetian,
    Pali,
    Pashto,
    Persian,
    Polish,
    Portuguese,
    Punjabi,
    Quechua,
    Romanian,
    Romansh,
    Rundi,
    Russian,
    NorthernSami,
    Samoan,
    Sango,
    Sanskrit,
    Sardinian,
    Serbian,
    Shona,
    Sindhi,
    Sinhala,
    Slovak,
    Slovenian,
    Somali,
    SouthernSotho,
    Spanish,
    Sundanese,
    Swahili,
    Swati,
    Swedish,
    Tagalog,
    Tahitian,
    Tajik,
    Tamil,
    Tatar,
    Telugu,
    Thai,
    Tibetan,
    Tigrinya,
    Tonga,
    Tsonga,
    Tswana,
    Turkish,
    Turkmen,
    Twi,
    Uighur,
    Ukrainian,
    Urdu,
    Uzbek,
    Venda,
    Vietnamese,
    Volapük,
    Walloon,
    Welsh,
    Wolof,
    Xhosa,
    SichuanYi,
    Yiddish,
    Yoruba,
    Zhuang,
    Zulu,
}

impl LanguageCode {
    pub fn to_iso639_2t(&self) -> &'static str {
        use LanguageCode as L;
        match self {
            L::Abkhazian => "abk",
            L::Afar => "aar",
            L::Afrikaans => "afr",
            L::Akan => "aka",
            L::Albanian => "sqi",
            L::Amharic => "amh",
            L::Arabic => "ara",
            L::Aragonese => "arg",
            L::Armenian => "hye",
            L::Assamese => "asm",
            L::Avaric => "ava",
            L::Avestan => "ave",
            L::Aymara => "aym",
            L::Azerbaijani => "aze",
            L::Bambara => "bam",
            L::Bashkir => "bak",
            L::Basque => "eus",
            L::Belarusian => "bel",
            L::Bengali => "ben",
            L::Bislama => "bis",
            L::Bosnian => "bos",
            L::Breton => "bre",
            L::Bulgarian => "bul",
            L::Burmese => "mya",
            L::Catalan => "cat",
            L::Chamorro => "cha",
            L::Chechen => "che",
            L::Chichewa => "nya",
            L::Chinese => "zho",
            L::ChurchSlavonic => "chu",
            L::Chuvash => "chv",
            L::Cornish => "cor",
            L::Corsican => "cos",
            L::Cree => "cre",
            L::Croatian => "hrv",
            L::Czech => "ces",
            L::Danish => "dan",
            L::Divehi => "div",
            L::Dutch => "nld",
            L::Dzongkha => "dzo",
            L::English => "eng",
            L::Esperanto => "epo",
            L::Estonian => "est",
            L::Ewe => "ewe",
            L::Faroese => "fao",
            L::Fijian => "fij",
            L::Finnish => "fin",
            L::French => "fra",
            L::WesternFrisian => "fry",
            L::Fulah => "ful",
            L::Gaelic => "gla",
            L::Galician => "glg",
            L::Ganda => "lug",
            L::Georgian => "kat",
            L::German => "deu",
            L::Greek => "ell",
            L::Kalaallisut => "kal",
            L::Guarani => "grn",
            L::Gujarati => "guj",
            L::Haitian => "hat",
            L::Hausa => "hau",
            L::Hebrew => "heb",
            L::Herero => "her",
            L::Hindi => "hin",
            L::HiriMotu => "hmo",
            L::Hungarian => "hun",
            L::Icelandic => "isl",
            L::Ido => "ido",
            L::Igbo => "ibo",
            L::Indonesian => "ind",
            L::Interlingua => "ina",
            L::Interlingue => "ile",
            L::Inuktitut => "iku",
            L::Inupiaq => "ipk",
            L::Irish => "gle",
            L::Italian => "ita",
            L::Japanese => "jpn",
            L::Javanese => "jav",
            L::Kannada => "kan",
            L::Kanuri => "kau",
            L::Kashmiri => "kas",
            L::Kazakh => "kaz",
            L::CentralKhmer => "khm",
            L::Kikuyu => "kik",
            L::Kinyarwanda => "kin",
            L::Kyrgyz => "kir",
            L::Komi => "kom",
            L::Kongo => "kon",
            L::Korean => "kor",
            L::Kuanyama => "kua",
            L::Kurdish => "kur",
            L::Lao => "lao",
            L::Latin => "lat",
            L::Latvian => "lav",
            L::Limburgan => "lim",
            L::Lingala => "lin",
            L::Lithuanian => "lit",
            L::LubaKatanga => "lub",
            L::Luxembourgish => "ltz",
            L::Macedonian => "mkd",
            L::Malagasy => "mlg",
            L::Malay => "msa",
            L::Malayalam => "mal",
            L::Maltese => "mlt",
            L::Manx => "glv",
            L::Maori => "mri",
            L::Marathi => "mar",
            L::Marshallese => "mah",
            L::Mongolian => "mon",
            L::Nauru => "nau",
            L::Navajo => "nav",
            L::NorthNdebele => "nde",
            L::SouthNdebele => "nbl",
            L::Ndonga => "ndo",
            L::Nepali => "nep",
            L::Norwegian => "nor",
            L::NorwegianBokmål => "nob",
            L::NorwegianNynorsk => "nno",
            L::Occitan => "oci",
            L::Ojibwa => "oji",
            L::Oriya => "ori",
            L::Oromo => "orm",
            L::Ossetian => "oss",
            L::Pali => "pli",
            L::Pashto => "pus",
            L::Persian => "fas",
            L::Polish => "pol",
            L::Portuguese => "por",
            L::Punjabi => "pan",
            L::Quechua => "que",
            L::Romanian => "ron",
            L::Romansh => "roh",
            L::Rundi => "run",
            L::Russian => "rus",
            L::NorthernSami => "sme",
            L::Samoan => "smo",
            L::Sango => "sag",
            L::Sanskrit => "san",
            L::Sardinian => "srd",
            L::Serbian => "srp",
            L::Shona => "sna",
            L::Sindhi => "snd",
            L::Sinhala => "sin",
            L::Slovak => "slk",
            L::Slovenian => "slv",
            L::Somali => "som",
            L::SouthernSotho => "sot",
            L::Spanish => "spa",
            L::Sundanese => "sun",
            L::Swahili => "swa",
            L::Swati => "ssw",
            L::Swedish => "swe",
            L::Tagalog => "tgl",
            L::Tahitian => "tah",
            L::Tajik => "tgk",
            L::Tamil => "tam",
            L::Tatar => "tat",
            L::Telugu => "tel",
            L::Thai => "tha",
            L::Tibetan => "bod",
            L::Tigrinya => "tir",
            L::Tonga => "ton",
            L::Tsonga => "tso",
            L::Tswana => "tsn",
            L::Turkish => "tur",
            L::Turkmen => "tuk",
            L::Twi => "twi",
            L::Uighur => "uig",
            L::Ukrainian => "ukr",
            L::Urdu => "urd",
            L::Uzbek => "uzb",
            L::Venda => "ven",
            L::Vietnamese => "vie",
            L::Volapük => "vol",
            L::Walloon => "wln",
            L::Welsh => "cym",
            L::Wolof => "wol",
            L::Xhosa => "xho",
            L::SichuanYi => "iii",
            L::Yiddish => "yid",
            L::Yoruba => "yor",
            L::Zhuang => "zha",
            L::Zulu => "zul",
        }
    }
}

impl TryFrom<&str> for LanguageCode {
    type Error = Error;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        use LanguageCode as L;
        let result = match value {
            "abk" => L::Abkhazian,
            "aar" => L::Afar,
            "afr" => L::Afrikaans,
            "aka" => L::Akan,
            "sqi" => L::Albanian,
            "amh" => L::Amharic,
            "ara" => L::Arabic,
            "arg" => L::Aragonese,
            "hye" => L::Armenian,
            "asm" => L::Assamese,
            "ava" => L::Avaric,
            "ave" => L::Avestan,
            "aym" => L::Aymara,
            "aze" => L::Azerbaijani,
            "bam" => L::Bambara,
            "bak" => L::Bashkir,
            "eus" => L::Basque,
            "bel" => L::Belarusian,
            "ben" => L::Bengali,
            "bis" => L::Bislama,
            "bos" => L::Bosnian,
            "bre" => L::Breton,
            "bul" => L::Bulgarian,
            "mya" => L::Burmese,
            "cat" => L::Catalan,
            "cha" => L::Chamorro,
            "che" => L::Chechen,
            "nya" => L::Chichewa,
            "zho" => L::Chinese,
            "chu" => L::ChurchSlavonic,
            "chv" => L::Chuvash,
            "cor" => L::Cornish,
            "cos" => L::Corsican,
            "cre" => L::Cree,
            "hrv" => L::Croatian,
            "ces" => L::Czech,
            "dan" => L::Danish,
            "div" => L::Divehi,
            "nld" => L::Dutch,
            "dzo" => L::Dzongkha,
            "eng" => L::English,
            "epo" => L::Esperanto,
            "est" => L::Estonian,
            "ewe" => L::Ewe,
            "fao" => L::Faroese,
            "fij" => L::Fijian,
            "fin" => L::Finnish,
            "fra" => L::French,
            "fry" => L::WesternFrisian,
            "ful" => L::Fulah,
            "gla" => L::Gaelic,
            "glg" => L::Galician,
            "lug" => L::Ganda,
            "kat" => L::Georgian,
            "deu" => L::German,
            "ell" => L::Greek,
            "kal" => L::Kalaallisut,
            "grn" => L::Guarani,
            "guj" => L::Gujarati,
            "hat" => L::Haitian,
            "hau" => L::Hausa,
            "heb" => L::Hebrew,
            "her" => L::Herero,
            "hin" => L::Hindi,
            "hmo" => L::HiriMotu,
            "hun" => L::Hungarian,
            "isl" => L::Icelandic,
            "ido" => L::Ido,
            "ibo" => L::Igbo,
            "ind" => L::Indonesian,
            "ina" => L::Interlingua,
            "ile" => L::Interlingue,
            "iku" => L::Inuktitut,
            "ipk" => L::Inupiaq,
            "gle" => L::Irish,
            "ita" => L::Italian,
            "jpn" => L::Japanese,
            "jav" => L::Javanese,
            "kan" => L::Kannada,
            "kau" => L::Kanuri,
            "kas" => L::Kashmiri,
            "kaz" => L::Kazakh,
            "khm" => L::CentralKhmer,
            "kik" => L::Kikuyu,
            "kin" => L::Kinyarwanda,
            "kir" => L::Kyrgyz,
            "kom" => L::Komi,
            "kon" => L::Kongo,
            "kor" => L::Korean,
            "kua" => L::Kuanyama,
            "kur" => L::Kurdish,
            "lao" => L::Lao,
            "lat" => L::Latin,
            "lav" => L::Latvian,
            "lim" => L::Limburgan,
            "lin" => L::Lingala,
            "lit" => L::Lithuanian,
            "lub" => L::LubaKatanga,
            "ltz" => L::Luxembourgish,
            "mkd" => L::Macedonian,
            "mlg" => L::Malagasy,
            "msa" => L::Malay,
            "mal" => L::Malayalam,
            "mlt" => L::Maltese,
            "glv" => L::Manx,
            "mri" => L::Maori,
            "mar" => L::Marathi,
            "mah" => L::Marshallese,
            "mon" => L::Mongolian,
            "nau" => L::Nauru,
            "nav" => L::Navajo,
            "nde" => L::NorthNdebele,
            "nbl" => L::SouthNdebele,
            "ndo" => L::Ndonga,
            "nep" => L::Nepali,
            "nor" => L::Norwegian,
            "nob" => L::NorwegianBokmål,
            "nno" => L::NorwegianNynorsk,
            "oci" => L::Occitan,
            "oji" => L::Ojibwa,
            "ori" => L::Oriya,
            "orm" => L::Oromo,
            "oss" => L::Ossetian,
            "pli" => L::Pali,
            "pus" => L::Pashto,
            "fas" => L::Persian,
            "pol" => L::Polish,
            "por" => L::Portuguese,
            "pan" => L::Punjabi,
            "que" => L::Quechua,
            "ron" => L::Romanian,
            "roh" => L::Romansh,
            "run" => L::Rundi,
            "rus" => L::Russian,
            "sme" => L::NorthernSami,
            "smo" => L::Samoan,
            "sag" => L::Sango,
            "san" => L::Sanskrit,
            "srd" => L::Sardinian,
            "srp" => L::Serbian,
            "sna" => L::Shona,
            "snd" => L::Sindhi,
            "sin" => L::Sinhala,
            "slk" => L::Slovak,
            "slv" => L::Slovenian,
            "som" => L::Somali,
            "sot" => L::SouthernSotho,
            "spa" => L::Spanish,
            "sun" => L::Sundanese,
            "swa" => L::Swahili,
            "ssw" => L::Swati,
            "swe" => L::Swedish,
            "tgl" => L::Tagalog,
            "tah" => L::Tahitian,
            "tgk" => L::Tajik,
            "tam" => L::Tamil,
            "tat" => L::Tatar,
            "tel" => L::Telugu,
            "tha" => L::Thai,
            "bod" => L::Tibetan,
            "tir" => L::Tigrinya,
            "ton" => L::Tonga,
            "tso" => L::Tsonga,
            "tsn" => L::Tswana,
            "tur" => L::Turkish,
            "tuk" => L::Turkmen,
            "twi" => L::Twi,
            "uig" => L::Uighur,
            "ukr" => L::Ukrainian,
            "urd" => L::Urdu,
            "uzb" => L::Uzbek,
            "ven" => L::Venda,
            "vie" => L::Vietnamese,
            "vol" => L::Volapük,
            "wln" => L::Walloon,
            "cym" => L::Welsh,
            "wol" => L::Wolof,
            "xho" => L::Xhosa,
            "iii" => L::SichuanYi,
            "yid" => L::Yiddish,
            "yor" => L::Yoruba,
            "zha" => L::Zhuang,
            "zul" => L::Zulu,
            _ => return Err(Error {}),
        };
        Ok(result)
    }
}

#[derive(Debug)]
pub struct Error {}

impl std::error::Error for Error {}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_fmt(format_args!("self:#?"))
    }
}
