use std::fmt::Display;

#[derive(Debug, serde::Serialize, serde::Deserialize, PartialEq, Eq, Clone)]
#[serde(rename_all = "lowercase")]
pub enum LanguageCode {
    Ab,
    Aa,
    Af,
    Ak,
    Sq,
    Am,
    Ar,
    An,
    Hy,
    // As,
    Av,
    Ae,
    Ay,
    Az,
    Bm,
    Ba,
    Eu,
    Be,
    Bn,
    Bi,
    Bs,
    Br,
    Bg,
    My,
    Ca,
    Ch,
    Ce,
    Ny,
    Zh,
    Cu,
    Cv,
    Kw,
    Co,
    Cr,
    Hr,
    Cs,
    Da,
    Dv,
    Nl,
    Dz,
    En,
    Eo,
    Et,
    Ee,
    Fo,
    Fj,
    Fi,
    Fr,
    Fy,
    Ff,
    Gd,
    Gl,
    Lg,
    Ka,
    De,
    El,
    Kl,
    Gn,
    Gu,
    Ht,
    Ha,
    He,
    Hz,
    Hi,
    Ho,
    Hu,
    // Is,
    Io,
    Ig,
    Id,
    Ia,
    Ie,
    Iu,
    Ik,
    Ga,
    It,
    Ja,
    Jv,
    Kn,
    Kr,
    Ks,
    Kk,
    Km,
    Ki,
    Rw,
    Ky,
    Kv,
    Kg,
    Ko,
    Kj,
    Ku,
    Lo,
    La,
    Lv,
    Li,
    Ln,
    Lt,
    Lu,
    Lb,
    Mk,
    Mg,
    Ms,
    Ml,
    Mt,
    Gv,
    Mi,
    Mr,
    Mh,
    Mn,
    Na,
    Nv,
    Nd,
    Nr,
    Ng,
    Ne,
    No,
    Nb,
    Nn,
    Oc,
    Oj,
    Or,
    Om,
    Os,
    Pi,
    Ps,
    Fa,
    Pl,
    Pt,
    Pa,
    Qu,
    Ro,
    Rm,
    Rn,
    Ru,
    Se,
    Sm,
    Sg,
    Sa,
    Sc,
    Sr,
    Sn,
    Sd,
    Si,
    Sk,
    Sl,
    So,
    St,
    Es,
    Su,
    Sw,
    Ss,
    Sv,
    Tl,
    Ty,
    Tg,
    Ta,
    Tt,
    Te,
    Th,
    Bo,
    Ti,
    To,
    Ts,
    Tn,
    Tr,
    Tk,
    Tw,
    Ug,
    Uk,
    Ur,
    Uz,
    Ve,
    Vi,
    Vo,
    Wa,
    Cy,
    Wo,
    Xh,
    Yi,
    Yo,
    Za,
    Zu,
}

impl Display for LanguageCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        use LanguageCode as L;
        let str = match self {
            L::Ab => "ab",
            L::Aa => "aa",
            L::Af => "af",
            L::Ak => "ak",
            L::Sq => "sq",
            L::Am => "am",
            L::Ar => "ar",
            L::An => "an",
            L::Hy => "hy",
            // L::As => "as",
            L::Av => "av",
            L::Ae => "ae",
            L::Ay => "ay",
            L::Az => "az",
            L::Bm => "bm",
            L::Ba => "ba",
            L::Eu => "eu",
            L::Be => "be",
            L::Bn => "bn",
            L::Bi => "bi",
            L::Bs => "bs",
            L::Br => "br",
            L::Bg => "bg",
            L::My => "my",
            L::Ca => "ca",
            L::Ch => "ch",
            L::Ce => "ce",
            L::Ny => "ny",
            L::Zh => "zh",
            L::Cu => "cu",
            L::Cv => "cv",
            L::Kw => "kw",
            L::Co => "co",
            L::Cr => "cr",
            L::Hr => "hr",
            L::Cs => "cs",
            L::Da => "da",
            L::Dv => "dv",
            L::Nl => "nl",
            L::Dz => "dz",
            L::En => "en",
            L::Eo => "eo",
            L::Et => "et",
            L::Ee => "ee",
            L::Fo => "fo",
            L::Fj => "fj",
            L::Fi => "fi",
            L::Fr => "fr",
            L::Fy => "fy",
            L::Ff => "ff",
            L::Gd => "gd",
            L::Gl => "gl",
            L::Lg => "lg",
            L::Ka => "ka",
            L::De => "de",
            L::El => "el",
            L::Kl => "kl",
            L::Gn => "gn",
            L::Gu => "gu",
            L::Ht => "ht",
            L::Ha => "ha",
            L::He => "he",
            L::Hz => "hz",
            L::Hi => "hi",
            L::Ho => "ho",
            L::Hu => "hu",
            // L::Is => "is",
            L::Io => "io",
            L::Ig => "ig",
            L::Id => "id",
            L::Ia => "ia",
            L::Ie => "ie",
            L::Iu => "iu",
            L::Ik => "ik",
            L::Ga => "ga",
            L::It => "it",
            L::Ja => "ja",
            L::Jv => "jv",
            L::Kn => "kn",
            L::Kr => "kr",
            L::Ks => "ks",
            L::Kk => "kk",
            L::Km => "km",
            L::Ki => "ki",
            L::Rw => "rw",
            L::Ky => "ky",
            L::Kv => "kv",
            L::Kg => "kg",
            L::Ko => "ko",
            L::Kj => "kj",
            L::Ku => "ku",
            L::Lo => "lo",
            L::La => "la",
            L::Lv => "lv",
            L::Li => "li",
            L::Ln => "ln",
            L::Lt => "lt",
            L::Lu => "lu",
            L::Lb => "lb",
            L::Mk => "mk",
            L::Mg => "mg",
            L::Ms => "ms",
            L::Ml => "ml",
            L::Mt => "mt",
            L::Gv => "gv",
            L::Mi => "mi",
            L::Mr => "mr",
            L::Mh => "mh",
            L::Mn => "mn",
            L::Na => "na",
            L::Nv => "nv",
            L::Nd => "nd",
            L::Nr => "nr",
            L::Ng => "ng",
            L::Ne => "ne",
            L::No => "no",
            L::Nb => "nb",
            L::Nn => "nn",
            L::Oc => "oc",
            L::Oj => "oj",
            L::Or => "or",
            L::Om => "om",
            L::Os => "os",
            L::Pi => "pi",
            L::Ps => "ps",
            L::Fa => "fa",
            L::Pl => "pl",
            L::Pt => "pt",
            L::Pa => "pa",
            L::Qu => "qu",
            L::Ro => "ro",
            L::Rm => "rm",
            L::Rn => "rn",
            L::Ru => "ru",
            L::Se => "se",
            L::Sm => "sm",
            L::Sg => "sg",
            L::Sa => "sa",
            L::Sc => "sc",
            L::Sr => "sr",
            L::Sn => "sn",
            L::Sd => "sd",
            L::Si => "si",
            L::Sk => "sk",
            L::Sl => "sl",
            L::So => "so",
            L::St => "st",
            L::Es => "es",
            L::Su => "su",
            L::Sw => "sw",
            L::Ss => "ss",
            L::Sv => "sv",
            L::Tl => "tl",
            L::Ty => "ty",
            L::Tg => "tg",
            L::Ta => "ta",
            L::Tt => "tt",
            L::Te => "te",
            L::Th => "th",
            L::Bo => "bo",
            L::Ti => "ti",
            L::To => "to",
            L::Ts => "ts",
            L::Tn => "tn",
            L::Tr => "tr",
            L::Tk => "tk",
            L::Tw => "tw",
            L::Ug => "ug",
            L::Uk => "uk",
            L::Ur => "ur",
            L::Uz => "uz",
            L::Ve => "ve",
            L::Vi => "vi",
            L::Vo => "vo",
            L::Wa => "wa",
            L::Cy => "cy",
            L::Wo => "wo",
            L::Xh => "xh",
            L::Yi => "yi",
            L::Yo => "yo",
            L::Za => "za",
            L::Zu => "zu",
        };
        f.write_str(str)
    }
}

impl TryFrom<&str> for LanguageCode {
    type Error = Error;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        use LanguageCode as L;
        let result = match value {
            "ab" => L::Ab,
            "aa" => L::Aa,
            "af" => L::Af,
            "ak" => L::Ak,
            "sq" => L::Sq,
            "am" => L::Am,
            "ar" => L::Ar,
            "an" => L::An,
            "hy" => L::Hy,
            // "as" => L::As,
            "av" => L::Av,
            "ae" => L::Ae,
            "ay" => L::Ay,
            "az" => L::Az,
            "bm" => L::Bm,
            "ba" => L::Ba,
            "eu" => L::Eu,
            "be" => L::Be,
            "bn" => L::Bn,
            "bi" => L::Bi,
            "bs" => L::Bs,
            "br" => L::Br,
            "bg" => L::Bg,
            "my" => L::My,
            "ca" => L::Ca,
            "ch" => L::Ch,
            "ce" => L::Ce,
            "ny" => L::Ny,
            "zh" => L::Zh,
            "cu" => L::Cu,
            "cv" => L::Cv,
            "kw" => L::Kw,
            "co" => L::Co,
            "cr" => L::Cr,
            "hr" => L::Hr,
            "cs" => L::Cs,
            "da" => L::Da,
            "dv" => L::Dv,
            "nl" => L::Nl,
            "dz" => L::Dz,
            "en" => L::En,
            "eo" => L::Eo,
            "et" => L::Et,
            "ee" => L::Ee,
            "fo" => L::Fo,
            "fj" => L::Fj,
            "fi" => L::Fi,
            "fr" => L::Fr,
            "fy" => L::Fy,
            "ff" => L::Ff,
            "gd" => L::Gd,
            "gl" => L::Gl,
            "lg" => L::Lg,
            "ka" => L::Ka,
            "de" => L::De,
            "el" => L::El,
            "kl" => L::Kl,
            "gn" => L::Gn,
            "gu" => L::Gu,
            "ht" => L::Ht,
            "ha" => L::Ha,
            "he" => L::He,
            "hz" => L::Hz,
            "hi" => L::Hi,
            "ho" => L::Ho,
            "hu" => L::Hu,
            // "is" => L::Is,
            "io" => L::Io,
            "ig" => L::Ig,
            "id" => L::Id,
            "ia" => L::Ia,
            "ie" => L::Ie,
            "iu" => L::Iu,
            "ik" => L::Ik,
            "ga" => L::Ga,
            "it" => L::It,
            "ja" => L::Ja,
            "jv" => L::Jv,
            "kn" => L::Kn,
            "kr" => L::Kr,
            "ks" => L::Ks,
            "kk" => L::Kk,
            "km" => L::Km,
            "ki" => L::Ki,
            "rw" => L::Rw,
            "ky" => L::Ky,
            "kv" => L::Kv,
            "kg" => L::Kg,
            "ko" => L::Ko,
            "kj" => L::Kj,
            "ku" => L::Ku,
            "lo" => L::Lo,
            "la" => L::La,
            "lv" => L::Lv,
            "li" => L::Li,
            "ln" => L::Ln,
            "lt" => L::Lt,
            "lu" => L::Lu,
            "lb" => L::Lb,
            "mk" => L::Mk,
            "mg" => L::Mg,
            "ms" => L::Ms,
            "ml" => L::Ml,
            "mt" => L::Mt,
            "gv" => L::Gv,
            "mi" => L::Mi,
            "mr" => L::Mr,
            "mh" => L::Mh,
            "mn" => L::Mn,
            "na" => L::Na,
            "nv" => L::Nv,
            "nd" => L::Nd,
            "nr" => L::Nr,
            "ng" => L::Ng,
            "ne" => L::Ne,
            "no" => L::No,
            "nb" => L::Nb,
            "nn" => L::Nn,
            "oc" => L::Oc,
            "oj" => L::Oj,
            "or" => L::Or,
            "om" => L::Om,
            "os" => L::Os,
            "pi" => L::Pi,
            "ps" => L::Ps,
            "fa" => L::Fa,
            "pl" => L::Pl,
            "pt" => L::Pt,
            "pa" => L::Pa,
            "qu" => L::Qu,
            "ro" => L::Ro,
            "rm" => L::Rm,
            "rn" => L::Rn,
            "ru" => L::Ru,
            "se" => L::Se,
            "sm" => L::Sm,
            "sg" => L::Sg,
            "sa" => L::Sa,
            "sc" => L::Sc,
            "sr" => L::Sr,
            "sn" => L::Sn,
            "sd" => L::Sd,
            "si" => L::Si,
            "sk" => L::Sk,
            "sl" => L::Sl,
            "so" => L::So,
            "st" => L::St,
            "es" => L::Es,
            "su" => L::Su,
            "sw" => L::Sw,
            "ss" => L::Ss,
            "sv" => L::Sv,
            "tl" => L::Tl,
            "ty" => L::Ty,
            "tg" => L::Tg,
            "ta" => L::Ta,
            "tt" => L::Tt,
            "te" => L::Te,
            "th" => L::Th,
            "bo" => L::Bo,
            "ti" => L::Ti,
            "to" => L::To,
            "ts" => L::Ts,
            "tn" => L::Tn,
            "tr" => L::Tr,
            "tk" => L::Tk,
            "tw" => L::Tw,
            "ug" => L::Ug,
            "uk" => L::Uk,
            "ur" => L::Ur,
            "uz" => L::Uz,
            "ve" => L::Ve,
            "vi" => L::Vi,
            "vo" => L::Vo,
            "wa" => L::Wa,
            "cy" => L::Cy,
            "wo" => L::Wo,
            "xh" => L::Xh,
            "yi" => L::Yi,
            "yo" => L::Yo,
            "za" => L::Za,
            "zu" => L::Zu,
            _ => return Err(Self::Error {}),
        };
        Ok(result)
    }
}

#[derive(Debug)]
pub struct Error {}

impl std::error::Error for Error {}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_fmt(format_args!("self:#?"))
    }
}
