[package]
name = "shared_types"
edition = "2024"

[dependencies]

[build-dependencies]
anyhow.workspace = true
domain = { path = "../domain" }
crux_core = { workspace = true, features = ["typegen"] }
shared = { path = "../shared", features = ["typegen"] }
